# Generated by Django 2.0.1 on 2018-01-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('is_primary', models.BooleanField(default=False)),
                ('mw_property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='contents.Property')),
            ],
        ),
    ]
