# Generated by Django 2.0.1 on 2018-01-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_propertyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='completion_statis',
            new_name='completion_status',
        ),
    ]
