# Generated by Django 2.0.1 on 2018-01-05 15:32

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20180105_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geocode',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
